---
# YAML linting configuration for Helm charts
extends: default

rules:
  # Allow longer lines in values.yaml for readability
  line-length:
    max: 120
    level: warning

  # Allow multiple documents in one file (common in K8s manifests)
  document-start: disable

  # Relaxed indentation for Helm charts
  indentation:
    spaces: 2
    indent-sequences: true

  # Allow truthy values (yes/no, on/off are common in Helm)
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off']
    check-keys: false

  # Comments don't need to be indented consistently
  comments-indentation: disable

  # Allow empty values (common in values.yaml)
  empty-values:
    forbid-in-block-mappings: false
    forbid-in-flow-mappings: false
