apiVersion: v2
name: endorser-service
description: A Helm chart for ACA-Py Endorser Service

type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: acapy
    version: "0.2.3"
    repository: "https://openwallet-foundation.github.io/helm-charts/"
    condition: acapy.enabled
  - name: postgresql
    version: "16.3.2"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
