{{- if not .Values.api.secret.existingSecret }}
{{ $apiSecretName := (include "endorser-service.apiSecretName" .) }}
{{ $endorserAdminApiKey := include "getOrGeneratePass" (dict "Namespace" .Release.Namespace "Kind" "Secret" "Name" $apiSecretName "Key" "endorserAdminApiKey" "Length" 32) }}
{{ $webhookApiKey := include "getOrGeneratePass" (dict "Namespace" .Release.Namespace "Kind" "Secret" "Name" $apiSecretName "Key" "webhookApiKey" "Length" 32) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $apiSecretName }}
  labels:
    {{- include "endorser-service.labels" . | nindent 4 }}
type: Opaque
data:
  endorser-admin-api-key: {{ $endorserAdminApiKey | b64enc }}
  webhook-api-key: {{ $webhookApiKey | b64enc }}
{{- end }}
