apiVersion: v2
name: vc-authn-oidc
description: A Helm chart to deploy ACAPy VC-AuthN on OpenShift
type: application

appVersion: "2.2.3"
version: 0.3.2

maintainers:
  - email: emiliano.sune@quartech.com
    name: esune
    url: https://github.com/esune
  - email: ivan.polchenko@quartech.com
    name: i5okie
    url: https://github.com/i5okie

# Charts the vc-authn-oidc service depends on
dependencies:
  - name: mongodb
    version: 16.4.1
    repository: "https://charts.bitnami.com/bitnami"
  - name: postgresql
    version: 15.5.38
    repository: https://charts.bitnami.com/bitnami/
    condition: postgresql.enabled
  - name: common
    repository: "https://charts.bitnami.com/bitnami"
    tags:
      - bitnami-common
    version: 2.x.x
