{{- if and .Values.acapy.networkPolicy.enabled .Values.acapy.networkPolicy.ingress.enabled -}}
apiVersion: {{ include "common.capabilities.networkPolicy.apiVersion" . }}
kind: NetworkPolicy
metadata:
  name: {{ include "acapy.fullname" . }}-ingress
  labels:
    {{- include "acapy.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "acapy.selectorLabels" . | nindent 6 }}
  ingress:
     {{- if and .Values.ingress.enabled .Values.acapy.networkPolicy.ingress.enabled (or .Values.acapy.networkPolicy.ingress.namespaceSelector .Values.acapy.networkPolicy.ingress.podSelector) }}
    - from:
        {{- if .Values.acapy.networkPolicy.ingress.namespaceSelector }}
        - namespaceSelector:
            matchLabels:
              {{- include "common.tplvalues.render" (dict "value" .Values.acapy.networkPolicy.ingress.namespaceSelector "context" $) | nindent 14 }}
        {{- end }}
        {{- if .Values.acapy.networkPolicy.ingress.podSelector }}
        - podSelector:
            matchLabels:
              {{- include "common.tplvalues.render" (dict "value" .Values.acapy.networkPolicy.ingress.podSelector "context" $) | nindent 14 }}
        {{- end }}
    {{- end }}
  policyTypes:
    - Ingress
{{- end -}}
