name: Helm Chart CI/CD

on:
  pull_request:
    paths:
      - 'charts/**'
  push:
    branches:
      - main
    paths:
      - 'charts/**'

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.18.2

      - name: Add Helm repos from chart dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          npm install -g yq
          charts=$(cat changed.txt 2>/dev/null || find charts -mindepth 1 -maxdepth 1 -type d)
          repos=""
          for chart in $charts; do
            if [ -f "$chart/Chart.yaml" ]; then
              yq '.dependencies // [] | .[] | .repository' "$chart/Chart.yaml"
            fi
          done | sort | uniq | while read repo; do
            if [ -n "$repo" ]; then
              name=$(echo "$repo" | sed 's|https\?://||;s|/|_|g')
              helm repo add "$name" "$repo" || true
            fi
          done

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0

      - name: Lint changed charts
        run: ct lint --config .github/ct.yaml

      - name: Create kind cluster
        uses: helm/kind-action@v1

      - name: Test install changed charts
        run: ct install --config .github/ct.yaml

      - name: Find changed charts
        id: changed
        run: |
          ct list-changed --config .github/ct.yaml > changed.txt
          echo "charts=$(cat changed.txt | tr '\n' ',' | sed 's/,$//')" >> $GITHUB_OUTPUT

      - name: Check version and appVersion bump
        if: steps.changed.outputs.charts != ''
        run: |
          for chart in $(cat changed.txt); do
            echo "Checking $chart..."

            old_version=$(git show ${{ github.event.pull_request.base.sha }}:$chart/Chart.yaml 2>/dev/null | yq '.version' || echo "0.0.0")
            new_version=$(yq '.version' $chart/Chart.yaml)

            old_app=$(git show ${{ github.event.pull_request.base.sha }}:$chart/Chart.yaml 2>/dev/null | yq '.appVersion' || echo "0.0.0")
            new_app=$(yq '.appVersion' $chart/Chart.yaml)

            if [[ "$old_version" == "$new_version" ]]; then
              echo "❌ Chart version was not bumped in $chart (still $new_version)"
              exit 1
            fi

            if [[ "$old_app" == "$new_app" ]]; then
              echo "⚠️ Warning: appVersion for $chart is unchanged ($new_app). Not failing, but consider bumping."
            fi
          done

      - name: Set up Node.js for generators
        if: steps.changed.outputs.charts != ''
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install readme and changelog generators
        if: steps.changed.outputs.charts != ''
        run: |
          npm install -g @bitnami/readme-generator-for-helm conventional-changelog-cli conventional-changelog-conventionalcommits

      - name: Generate and check README and CHANGELOG
        if: steps.changed.outputs.charts != ''
        run: |
          need_update=""
          for chart in $(cat changed.txt); do
            # Generate README
            npx @bitnami/readme-generator-for-helm --readme $chart/README.md --values $chart/values.yaml
            # Check for uncommitted changes in README.md
            if ! git diff --exit-code -- $chart/README.md > /dev/null; then
              echo "❌ README.md for $chart is out of date. Please re-run the generator."
              need_update="yes"
            else
              echo "✅ README.md for $chart is up to date."
            fi

            # Check that CHANGELOG.md was updated
            if ! git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep -q "^$chart/CHANGELOG.md$"; then
              echo "❌ CHANGELOG.md not updated for $chart. Please run conventional-changelog-cli."
              need_update="yes"
            fi
          done
          if [ "$need_update" = "yes" ]; then
            exit 1
          fi

  publish:
    runs-on: ubuntu-latest
    needs: lint-test
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.18.2

      - name: Add Helm repos from chart dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          npm install -g yq
          charts=$(cat changed.txt 2>/dev/null || find charts -mindepth 1 -maxdepth 1 -type d)
          repos=""
          for chart in $charts; do
            if [ -f "$chart/Chart.yaml" ]; then
              yq '.dependencies // [] | .[] | .repository' "$chart/Chart.yaml"
            fi
          done | sort | uniq | while read repo; do
            if [ -n "$repo" ]; then
              name=$(echo "$repo" | sed 's|https\?://||;s|/|_|g')
              helm repo add "$name" "$repo" || true
            fi
          done

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0

      - name: Detect and package changed charts
        id: detect
        run: |
          mkdir -p .cr-release-packages
          mkdir -p .cr-existing-index

          # Clone existing gh-pages to get current index.yaml
          git fetch origin gh-pages
          git show origin/gh-pages:index.yaml > .cr-existing-index/index.yaml || echo "apiVersion: v1\nentries: {}\ngenerated: $(date -u +%Y-%m-%dT%H:%M:%SZ)" > .cr-existing-index/index.yaml

          # Find all charts in /charts
          charts=$(find charts -mindepth 1 -maxdepth 1 -type d)

          # Determine which ones need packaging
          to_package=""
          for chart in $charts; do
            name=$(yq '.name' $chart/Chart.yaml)
            version=$(yq '.version' $chart/Chart.yaml)

            existing_versions=$(yq eval ".entries[\"$name\"][].version // []" .cr-existing-index/index.yaml 2>/dev/null || true)

            if ! echo "$existing_versions" | grep -q "^$version$"; then
              echo "📦 New chart or version detected: $name-$version"
              helm package "$chart" --destination .cr-release-packages
              to_package+="$chart,"
            else
              echo "✔️ Chart $name version $version already exists in index"
            fi
          done

          to_package=${to_package%,} # Trim trailing comma
          echo "charts=$to_package" >> $GITHUB_OUTPUT

      - name: Update index.yaml
        if: steps.detect.outputs.charts != ''
        run: |
          helm repo index .cr-release-packages --url https://openwallet-foundation.github.io/helm-charts/

      - name: Deploy to GitHub Pages
        if: steps.detect.outputs.charts != ''
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .cr-release-packages
          publish_branch: gh-pages
