name: PR Chart Checks

on:
  pull_request:
    branches:
      - main
    paths:
      - 'charts/**'

jobs:
  chart-tests:
    name: Lint & Test Charts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.3

      - name: Add Helm repos from chart dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          npm install -g yq
          charts=$(cat changed.txt 2>/dev/null || find charts -mindepth 1 -maxdepth 1 -type d)
          repos=""
          for chart in $charts; do
            if [ -f "$chart/Chart.yaml" ]; then
              yq '.dependencies // [] | .[] | .repository' "$chart/Chart.yaml"
            fi
          done | sort | uniq | while read repo; do
            if [ -n "$repo" ]; then
              name=$(echo "$repo" | sed 's|https\?://||;s|/|_|g')
              helm repo add "$name" "$repo" || true
            fi
          done

      - name: Install chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: List changed charts
        id: list-changed
        run: |
          changed=$(ct list-changed --config .github/ct.yaml)
          echo "changed_charts<<EOF" >> $GITHUB_OUTPUT
          echo "$changed" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Lint changed charts
        run: ct lint --config .github/ct.yaml

      - name: Run chart tests (install, upgrade)
        run: ct install --config .github/ct.yaml

      - name: Check version and appVersion bump
        run: |
          for chart in ${{ steps.list-changed.outputs.changed_charts }}; do
            echo "Checking $chart..."

            old_version=$(git show origin/main:$chart/Chart.yaml | yq '.version')
            new_version=$(yq '.version' $chart/Chart.yaml)

            old_app=$(git show origin/main:$chart/Chart.yaml | yq '.appVersion')
            new_app=$(yq '.appVersion' $chart/Chart.yaml)

            if [[ "$old_version" == "$new_version" ]]; then
              echo "❌ Chart version was not bumped in $chart (still $new_version)"
              exit 1
            fi

            if [[ "$old_app" == "$new_app" ]]; then
              echo "⚠️ Warning: appVersion for $chart is unchanged ($new_app). Not failing, but consider bumping."
            fi
          done
